image: java:latest

stages:
  - pages

pages:
  stage: pages
  only:
    - master
  script:
    - /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d bin/ src/eggroll/apcsa/blackjack/*.java
    - cd bin
    - /usr/lib/jvm/java-8-openjdk-amd64/bin/jar -cvfm blackjack.jar ../build-dependencies/MANIFEST.MF eggroll/apcsa/blackjack/*.class
    - cd ../
    - mkdir public
    - cp bin/blackjack.jar public/blackjack.jar
  artifacts:
    paths:
      - public/*.jar
    expire_in: 1 year
